const ActionCartTypes = {
  TOGGLE_CART_VISABILITY: 'TOGGLE_CART_VISABILITY',
  ADD_ITEM: 'ADD_ITEM',
  DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY',
  REMOVE_ITEM: 'REMOVE_ITEM'
};

export default ActionCartTypes